services:
  readme.blog.postgres:
    image: postgres:14-alpine
    container_name: readme.blog.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - readme.postgres.blog:/var/lib/postgres/data

  readme.blog.pgadmin:
    image: dpage/pgadmin4
    container_name: readme.blog.pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    depends_on:
      - readme.blog.postgres
    networks:
      - readme.blog

volumes:
  readme.postgres.blog:

networks:
  readme.blog:
    driver: bridge
